### ISSUE TITLE
SEON - Generated Signed APK Issue

### ISSUE THREAD

**Issue by FoloosiApps** [Shahin-Sefidgaran/seon-flutter-sdk#9] opened 2024-06-21 09:36 UTC
Hi,

I am using SEON flutter SDK version 3.0.0. I get SEON _fingerPrintBase64 in debug build. Its working successfully. Then i get the generated signed APK, app is automatically closed. At the time i hidden the SEON integration code, its working fine. Please support this case.

Explain: FATAL EXCEPTION: main Process: com.example.customer,  PID: 22287 java.lang.NoSuchMethodError:  no static or non-static method "Lio/seon/androidsdk/ service/ JNIHandler; . getProdUrl( Ljava/ lang/ Object; ) Ljava/ lang/ String; "  at java.lang.Runtime.nativeLoad( Native Method) at java.lang.Runtime.nativeLoad( Runtime. java: 1126)  with tag AndroidRuntime

### My Source code:

```
final RxString _fingerPrintBase64 = "Fetching fingerprint...".obs;
var uuid = const Uuid();

 @override
  void onInit() {
  getSeonDetails(sessionId: uuid.v1());
  super.onInit();
}

Future<void> getSeonDetails({required sessionId}) async {
      String fingerPrintBase64;
      try {
        final _seonPlugin = SeonPlugin();
        fingerPrintBase64 = await _seonPlugin.getFingerPrintBase64(sessionId: sessionId, isLoggingEnabled: true) ?? 
        'Unknown fingerprint';
      } on PlatformException {
        fingerPrintBase64 = 'Failed to get fingerprint.';
      }
      _fingerPrintBase64.value = fingerPrintBase64;
      debugPrint('FingerPrintValue: ${_fingerPrintBase64.value}');
  }
```

**Comment by Shahin-Sefidgaran** [comment] 2024-07-21 07:22
Hi @FoloosiApps 
This issue is a duplicate of https://github.com/Shahin-Sefidgaran/seon-flutter-sdk/issues/8. I've closed this issue, but please refer to the original for further discussion.

**Closed as completed by Shahin-Sefidgaran** 2024-07-21 07:22 UTC
